# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

resources:
  containers:
  - container: wpilib2020
    image: wpilib/roborio-cross-ubuntu:2020-18.04

jobs:

 - job: Linux
   pool:
     vmImage: 'Ubuntu 16.04'

   container: wpilib2020

   steps:
   - task: Gradle@2
     inputs:
       workingDirectory: ''
       gradleWrapperFile: 'gradlew'
       gradleOptions: '-Xmx3072m'
       publishJUnitResults: true
       testResultsFiles: '**/TEST-*.xml'
       tasks: 'build publish'
       options: '-PciBuild'
       # checkStyleRunAnalysis: true
       # pmdRunAnalysis: true

   - task: PublishBuildArtifacts@1
     displayName: 'Publish Artifact: maven repo'
     inputs:
       PathtoPublish: 'build/maven_repo'
       ArtifactName: 'LinuxMaven'

 - job: Windows_64_Bit
   pool:
      vmImage: 'windows-2019'
   steps:
    - task: Gradle@2
      inputs:
        workingDirectory: ''
        gradleWrapperFile: 'gradlew'
        gradleOptions: '-Xmx3072m'
        jdkVersionOption: '1.11'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        tasks: 'build publish'
        options: '-PciBuild -Dhttp.socketTimeout=60000 -Dhttp.connectionTimeout=60000'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: maven repo'
      inputs:
        PathtoPublish: 'build/maven_repo'
        ArtifactName: 'Win64Maven'


 - job: Windows_32_Bit
   pool:
     vmImage: 'vs2017-win2016'
   steps:
    - powershell: |
        mkdir build
        $ProgressPreference = 'SilentlyContinue'
        wget "https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.4%2B11/OpenJDK11U-jdk_x86-32_windows_hotspot_11.0.4_11.zip" -O "build\jdk.zip"
      displayName: 'Download JDK'
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '11'
        jdkSourceOption: localDirectory
        jdkFile: 'build/jdk.zip'
        jdkDestinationDirectory: 'build/jdkinst'
        jdkArchitectureOption: x86
    - task: Gradle@2
      inputs:
        workingDirectory: ''
        gradleWrapperFile: 'gradlew'
        gradleOptions: '-Xmx1024m'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        tasks: 'build publish'
        options: '-PciBuild -Dhttp.socketTimeout=60000 -Dhttp.connectionTimeout=60000'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: maven repo'
      inputs:
        PathtoPublish: 'build/maven_repo'
        ArtifactName: 'Win32Maven'

 - job: Mac
   pool:
     vmImage: 'macOS-10.14'
   steps:
    - script: |
        mkdir build
        export JAVA_HOME=`/usr/libexec/java_home -v 11`
      displayName: 'Setup JDK'
    - task: Gradle@2
      inputs:
        workingDirectory: ''
        gradleWrapperFile: 'gradlew'
        gradleOptions: '-Xmx3072m'
        jdkVersionOption: '1.11'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        tasks: 'build publish'
        options: '-PciBuild -Dhttp.socketTimeout=60000 -Dhttp.connectionTimeout=60000'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: maven repo'
      inputs:
        PathtoPublish: 'build/maven_repo'
        ArtifactName: 'OSXMaven'

 - job: PrepareMaven
   pool:
     vmImage: 'ubuntu-16.04'
   steps:

    - task: DownloadBuildArtifacts@0
      displayName: 'Download Linux Artifacts'
      inputs:
        artifactName: 'LinuxMaven'
        downloadPath: $(System.DefaultWorkingDirectory)/linux

    - task: DownloadBuildArtifacts@0
      displayName: 'Download Windows 32 Artifacts'
      inputs:
        artifactName: 'Win32Maven'
        downloadPath: $(System.DefaultWorkingDirectory)/win32

    - task: DownloadBuildArtifacts@0
      displayName: 'Download Windows 64 Artifacts'
      inputs:
        artifactName: 'Win64Maven'
        downloadPath: $(System.DefaultWorkingDirectory)/win64

    - task: DownloadBuildArtifacts@0
      displayName: 'Download Build Artifacts'
      inputs:
        artifactName: 'OSXMaven'
        downloadPath: $(System.DefaultWorkingDirectory)/mac

    - powershell: |
        Copy-Item $(System.DefaultWorkingDirectory)/win32/Win32Maven/com $(System.DefaultWorkingDirectory)/output/com -recurse -force -verbose
        Copy-Item $(System.DefaultWorkingDirectory)/win64/Win64Maven/*   $(System.DefaultWorkingDirectory)/output     -recurse -force -verbose
        Copy-Item $(System.DefaultWorkingDirectory)/mac/OSXMaven/*       $(System.DefaultWorkingDirectory)/output     -recurse -force -verbose
        Copy-Item $(System.DefaultWorkingDirectory)/linux/LinuxMaven/*   $(System.DefaultWorkingDirectory)/output     -recurse -force -verbose

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Combined Artifacts'
      inputs:
        PathtoPublish: $(System.DefaultWorkingDirectory)/output
        ArtifactName: 'REV Full Maven'

   dependsOn: [ Windows_64_Bit, Windows_32_Bit, Mac, Linux ]
   condition: succeeded()
