/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_revrobotics_jni_CANSWDLJNI */

#ifndef _Included_com_revrobotics_jni_CANSWDLJNI
#define _Included_com_revrobotics_jni_CANSWDLJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_revrobotics_jni_CANSWDLJNI
 * Method:    AddDevice
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_com_revrobotics_jni_CANSWDLJNI_AddDevice
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     com_revrobotics_jni_CANSWDLJNI
 * Method:    RunSWDL
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_revrobotics_jni_CANSWDLJNI_RunSWDL
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
