/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_snobot_simulator_rev_RevSimJni */

#ifndef _Included_com_snobot_simulator_rev_RevSimJni
#define _Included_com_snobot_simulator_rev_RevSimJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_snobot_simulator_rev_RevSimJni
 * Method:    registerRevCallback
 * Signature: (Lcom/snobot/simulator/rev/RevCallback;)V
 */
JNIEXPORT void JNICALL Java_com_snobot_simulator_rev_RevSimJni_registerRevCallback
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_snobot_simulator_rev_RevSimJni
 * Method:    cancelRevCallback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_snobot_simulator_rev_RevSimJni_cancelRevCallback
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
